### ISSUE TITLE
Feature request: better default parsing of Rails error responses

### ISSUE THREAD

**Issue by bteitelb** [werein/x-editable-rails#16]
When returning Rails validation errors in the usual way:

``` ruby
format.json { render json: @obj.errors, status: :unprocessable_entity }
```

I get something like this:

![screen shot 2013-12-02 at 10 00 47 pm](https://f.cloud.github.com/assets/24629/1661421/90871606-5be0-11e3-9e7b-fd70ef3322e5.png)

When I really want this:

![screen shot 2013-12-02 at 10 01 10 pm](https://f.cloud.github.com/assets/24629/1661420/84f12192-5be0-11e3-900e-81e3608c044d.png)

To get that, I've written a default error handler to massage the JSONified Rails validation errors:

``` javascript
$.fn.editable.defaults.error = 
  function(response, newValue) { 
    var field_name = $(this).data('name'),
        error_msgs = response.responseJSON[field_name];
    return error_msgs.join("; ");
  };
```

Should something like this be built into x-editable-rails?

**Comment by bperucchi** [comment]
I wrote this method to show all object errors

```javascript
$('.editable').editable({
        mode: 'inline',
        showbuttons: false,
        error: function(response, newValue) { 
          var error_msgs = []
          $.each(response.responseJSON, function(key, value){ 
            error_msgs.push(key+' '+value)
          })
          return error_msgs.join("; ");
        }
      })
```

**Comment by SirRawlins** [comment]
@bperucchi your solution worked nicely for me. Have to say this was the biggest stumbling block for me when setting up x-editable-rails. I think the gem, and it's docs need to do a better job of explaining how they expect errors to be returned from the controller.

@jirikolarik could you explain what format the error response should come in? Both full object and the error messages? If so, how are you rendering that in your controllers?
