### ISSUE TITLE
several fields in dialog

### ISSUE THREAD

**Issue by ZuBB** [werein/x-editable-rails#34]
Hi!

original js extention supports multiple fields for i-place editing (see "Custom input, several fields" demo). Any ideas how to achieve this with your gem?

**Comment by gerryatvt** [comment]
Yes please. When an address is updated our app must re-calculate distances between people, we do not want to do this for every address field. Please provide an example of multiple-field, single call to the server.

**Comment by jbwl** [comment]
I'd also like to see this implemented

**Comment by jirikolarik** [comment]
You can use x-editable as usual without rails helpers, pull requests with implementing this functionality are welcome
