### ISSUE TITLE
too much recursion

### ISSUE THREAD

**Issue by bkd** [werein/x-editable-rails#46]
too much recursion editable_form.js:6
too much recursion editable_form.js:13

Im getting this error on the first load of the page. If I refresh the page it works fine

I have in my coffee script 

$(document).ready ->
  $(".editable").editable()
  return

Can anyone else advise if this is an issue or something I have done

Also on the wysihtml5 it doesnt work at all Im getting lots of errors

Use of Mutation Events is deprecated. Use MutationObserver instead. bootstrap3-wysihtml5.js:5
TypeError: b.nativeSelection is null bootstrap3-wysihtml5.js:4
NS_ERROR_FAILURE:  bootstrap3-wysihtml5.js:7

**Comment by goooseman** [comment]
Hi, 
this is the same issue, like this: https://github.com/werein/x-editable-rails/issues/37
Just use version from GitHub:
gem 'x-editable-rails', :git => 'https://github.com/werein/x-editable-rails'
