### ISSUE TITLE
Can't understand how to use this

### ISSUE THREAD

**Issue by feliperaul** [werein/x-editable-rails#64]
Sorry guys, but I can't understand this line in the docs

```%h1= editable @model, :name```

How am I supposed to use this inside a .html.erb view ?

Let's assume I have a h1 element I want to make x-editable in the view. What should I do ?

**Comment by jirikolarik** [comment]
That's haml syntax 
Use this in erb'''erb<h1><%= editable @model, name %></h1>'''
Von meinem iPhone gesendet

    _____________________________
