### ISSUE TITLE
Support for Rails 5? 

### ISSUE THREAD

**Issue by vl3** [werein/x-editable-rails#78]
I would like to ask if do you plan to add support for rails 5 or if it is already working... I didn't find any reference to this topic in the documentation.
Thanks !

**Comment by jirikolarik** [comment]
Hi, I don't actively use it anymore, so I can't say, but I don't see a reason, why it shouldn't work. Give it a shot ale let us know :)

**Comment by jirikolarik** [comment]
Looks like it's working fine on Rails 5

https://github.com/werein/x-editable-rails/pull/80#issuecomment-261708900
