### ISSUE TITLE
Release time?

### ISSUE THREAD

**Issue by d4mk0** [werein/x-editable-rails#93]
Guys I have spent a lot of time for debugging my problem in code like this:

```ruby
editable region, :country_id, source: countries.map { |country| { value: country.id, text: country.name } }, value: region.country.name
```

In release v1.5.5 it works incorrect, when i click on field, he doesn't find value in sources array...
But in master tree here it works really great with Rails 5.0.5.

May be its time for new release?

**Comment by jirikolarik** [comment]
Hi,

sure thing :)

**Comment by jirikolarik** [comment]
Bumped ;)

**Comment by d4mk0** [comment]
Very nice job! Thank you!!!
Also please dup this release to github release/tag pages.
